### ISSUE TITLE
Link to component page

### ISSUE THREAD

**Issue by Link2Twenty** [safetychanger/sc-timeago#4]
Hi, you could use https://elements.polymer-project.org/elements/iron-component-page to make a component page complete with demo.

Just an idea, but might make your components easier for people to just pick up and use.

Also if you add a link to the component page in the 'website' section at the top of the git customelements.io will add that link as a homepage on their elements page https://customelements.io/safetychanger/sc-timeago/ .

**Comment by rubenstolk** [comment]
Hey @Link2Twenty thanks, will have a look. In meanwhile, feel free to submit PR's.
